module.exports = {
    BASE_URL: BASE_URL,
    BASE_URL_FRONTEND : BASE_URL_FRONTEND,
    auth: BASE_URL + "auth/",
    clearToken: BASE_URL + "auth/clear-token/",
    authCheck: BASE_URL + "auth/check/",
    authCheckWithToken: BASE_URL + "auth/check-with-token/",
    authLogout: BASE_URL + "auth/logout/",
    authGetPermissions: BASE_URL + "auth/permissions/",
    dashboard: {
        stats: BASE_URL + "dashboard/",
    },
    usuarios: {
        perfil: BASE_URL + "usuarios/perfil/",
        usuarios: BASE_URL + "usuarios/usuarios/",
        permisos: BASE_URL + "usuarios/permisos/",
        grupos: BASE_URL + "usuarios/grupos/",
    },
    notas: {
        notas: BASE_URL + "notas/",
    },
    calendar: {
        tipoEventos: BASE_URL + "tipoeventos/",
        tipoEventosSelect: BASE_URL + "tipoeventos/select/",
        eventosCalendar: BASE_URL + "eventoscalendar/",
        eventosUsuario: BASE_URL + "eventoscalendar/usuario/",
    },
    comitentes: {
        comitentes: BASE_URL + "comitentes/comitentes/",
        comitentesCtaCte: BASE_URL + "comitentes/listctacte/",
        categorias: BASE_URL + "comitentes/categorias/",
        profesiones: BASE_URL + "comitentes/profesiones/",
        confirmacion: BASE_URL + "comitentes/confirmacion/",
        entidadesselect: BASE_URL + "comitentes/entidades/listall/",
    },
    geograficas: {
        provincias: BASE_URL + "geograficas/provincias/",
        provinciasSelect: BASE_URL + "geograficas/provincias/select/",
        localidades: BASE_URL + "geograficas/localidades/",
        localidadesSelect: BASE_URL + "geograficas/localidades/select/",
    },
    expedientes: {
        estadosencomienda: BASE_URL + "expedientes/estadosencomienda/",
        estadosencomiendaSelect: BASE_URL + "expedientes/estadosencomienda/select/",
        estadolotes: BASE_URL + "expedientes/estadolotes/",
        objetosdetrabajo: BASE_URL + "expedientes/objetosdetrabajo/",
        objetosdetrabajoSelect: BASE_URL + "expedientes/objetosdetrabajo/select/",
        tiposdeencomienda: BASE_URL + "expedientes/tiposdeencomienda/",
        tiposdeencomiendaSelect: BASE_URL + "expedientes/tiposdeencomienda/select/",
        situacionlotes: BASE_URL + "expedientes/situacionlotes/",

        encomiendaprofesional: BASE_URL + "expedientes/encomiendaprofesional/",
        encomiendaprofesionalarchivo: BASE_URL + "expedientes/encomiendaprofesional/archivoadjunto/",
        encomiendaprofesionalSelect: BASE_URL + "expedientes/encomiendaprofesional/select/",
        encomiendaUltimoNro: BASE_URL + "expedientes/encomiendaprofesional/ultimonro/",
        encomiendaCambioEstado: BASE_URL + "expedientes/encomiendaprofesional/cambioestado/",
        encomiendaCambioEstadoArchivo: BASE_URL + "expedientes/encomiendaprofesional/cambioestado/archivoadjunto/",
        encomiendaprofesionalEstadoDeuda: BASE_URL + "expedientes/encomiendaprofesional/estadodeuda/",

        encomiendadocumento: BASE_URL + "expedientes/encomiendaprofesional/$id_encomienda/documento/$id_archivo/",
        
        encomiendaAsignarDias: BASE_URL + "expedientes/encomiendaprofesional/asignardiasestimados/",

        fichaEncomienda: BASE_URL + "expedientes/encomiendaprofesional/fichaencomienda/$id_encomienda/",
    },
    mails: {
        config: BASE_URL + "mails/configuracionmail/",
        plantillas: BASE_URL + "mails/plantillas/",
        casillas: BASE_URL + "mails/casillas/",
        emailImages: BASE_URL + "mails/plantillas/uploadimage/",
    },
    cuentasCorrientes: {
        movimientos: BASE_URL + "cuentascorrientes/",
        estadoDeuda: BASE_URL + "cuentascorrientes/estadodeuda/",
        cobroAplicacion: BASE_URL + "cuentascorrientes/cobroaplicacion/",
        totalAplicacionesEIngresos: BASE_URL + "cuentascorrientes/totalaplicacioneseingresos/",
        mediosDePago: BASE_URL + "cuentascorrientes/mediosdepago/",
    },
    visaciones: {
        plantillas: BASE_URL + "visaciones/plantillas/",
        estados: BASE_URL + "visaciones/estadosplantilla/",
        estadosSelect: BASE_URL + "visaciones/estadosplantilla/select/",
        encomienda: BASE_URL + "visaciones/encomienda/",
        cambioestado: BASE_URL + "visaciones/encomienda/cambioestado/",
        archivo: BASE_URL + "visaciones/encomiendaprofesional/archivoadjunto/",
        listadovisacionesencomiendas: BASE_URL + "visaciones/encomienda/profesional/",
        agrupacionvisaciones: BASE_URL + "visaciones/agrupacionplantillas/",
        listagruposvisaciones: BASE_URL + "visaciones/getallgruposvisaciones/",
    },
    container: BASE_URL + "container/",
}
